services:
  app:
    build: .
    container_name: samarth-app
    restart: always
    ports:
      - "8080:80"
    env_file: .env
    networks:
      - samarth-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: samarth-mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: ""
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - samarth-network

  redis:
    image: redis:7-alpine
    container_name: samarth-redis
    restart: always
    networks:
      - samarth-network

networks:
  samarth-network:
volumes:
  mysql_data:
